from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime
from .serializers import CSVUploadSerializer
from .models import EquipmentSummary
import pandas as pd


class UploadCSV(APIView):
    parser_classes = (MultiPartParser, FormParser)
    serializer_class = CSVUploadSerializer

    def post(self, request):
        serializer = CSVUploadSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        file = serializer.validated_data['file']
        df = pd.read_csv(file)

        summary = {
            "total_equipment": len(df),
            "avg_flowrate": df["Flowrate"].mean(),
            "avg_pressure": df["Pressure"].mean(),
            "avg_temperature": df["Temperature"].mean(),
            "type_distribution": df["Type"].value_counts().to_dict()
        }

        # Save to DB
        EquipmentSummary.objects.create(**summary)

        # Keep only last 5
        qs = EquipmentSummary.objects.order_by('-uploaded_at')
        if qs.count() > 5:
            for old in qs[5:]:
                old.delete()

        return Response(summary)


class SummaryView(APIView):
    def get(self, request):
        latest = EquipmentSummary.objects.order_by('-uploaded_at').first()
        if latest:
            data = {
                "total_equipment": latest.total_equipment,
                "avg_flowrate": latest.avg_flowrate,
                "avg_pressure": latest.avg_pressure,
                "avg_temperature": latest.avg_temperature,
                "type_distribution": latest.type_distribution,
                "uploaded_at": latest.uploaded_at
            }
            return Response(data)
        else:
            return Response({"detail": "No summary available. Please upload a CSV first."})


class HistoryView(APIView):
    def get(self, request):
        summaries = EquipmentSummary.objects.order_by('-uploaded_at')[:5]
        data = [
            {
                "total_equipment": s.total_equipment,
                "avg_flowrate": s.avg_flowrate,
                "avg_pressure": s.avg_pressure,
                "avg_temperature": s.avg_temperature,
                "type_distribution": s.type_distribution,
                "uploaded_at": s.uploaded_at
            }
            for s in summaries
        ]
        return Response(data)


# PDF Endpoint
def generate_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'

    p = canvas.Canvas(response, pagesize=letter)
    width, height = letter

    # Header
    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, height - 50, "Chemical Equipment Report")
    p.setFont("Helvetica", 10)
    p.drawString(50, height - 70, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Latest summary
    latest = EquipmentSummary.objects.order_by('-uploaded_at').first()
    if latest:
        p.setFont("Helvetica-Bold", 12)
        p.drawString(50, height - 100, "Summary Metrics:")
        p.setFont("Helvetica", 11)
        p.drawString(70, height - 120, f"Total Equipment: {latest.total_equipment}")
        p.drawString(70, height - 140, f"Avg Flowrate: {latest.avg_flowrate:.2f}")
        p.drawString(70, height - 160, f"Avg Pressure: {latest.avg_pressure:.2f}")
        p.drawString(70, height - 180, f"Avg Temperature: {latest.avg_temperature:.2f}")

    # Recent uploads
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, height - 220, "Recent Uploads:")
    p.setFont("Helvetica", 10)

    uploads = EquipmentSummary.objects.order_by('-uploaded_at')[:5]
    y = height - 240
    for u in uploads:
        p.drawString(70, y, f"{u.uploaded_at.strftime('%Y-%m-%d %H:%M')} | Total: {u.total_equipment} | Flowrate: {u.avg_flowrate:.2f} | Pressure: {u.avg_pressure:.2f} | Temp: {u.avg_temperature:.2f}")
        y -= 20

    # Footer
    p.setFont("Helvetica-Oblique", 9)
    p.drawString(50, 30, "Generated by Chemical Equipment Visualizer")

    p.showPage()
    p.save()
    return response